### ISSUE TITLE
[ML] No reason given when DFA process is killed due to OOM

### ISSUE THREAD

**Issue by sophiec20** [elastic/ml-cpp#1462]
Found in 8.0.0-SNAPSHOT `    "build_hash" : "2e4394c1735c1a449e815ece7a4fbb0ba3087c79",
    "build_date" : "2020-08-21T12:32:36.523469Z",`

The DFA job was being killed due to OOM. This took a while to diagnose because I had to find the logs on the particular node. 

Currently the message returned in job messages only says it stopped unexpectedly. Is it possible to get the reason? In this case `signal 9`.

If the process died due to a code fault, do we get more information?

```
[2020-08-22T13:57:09,620][DEBUG][o.e.x.m.d.p.AnalyticsResultProcessor] [node1] [z-ember-outlier4] progress for phase [computing_outliers] updated to [8]
[2020-08-22T13:57:16,792][DEBUG][o.e.x.m.d.p.AnalyticsResultProcessor] [node1] [z-ember-outlier4] progress for phase [computing_outliers] updated to [9]
[2020-08-22T13:57:30,363][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [node1] [controller/8928] [CDetachedProcessSpawner.cc@183] Child process with PID 12949 was terminated by signal 9
[2020-08-22T13:57:30,487][ERROR][o.e.x.m.p.AbstractNativeProcess] [node1] [z-ember-outlier4] analytics process stopped unexpectedly:
[2020-08-22T13:57:30,497][DEBUG][o.e.x.m.d.p.AnalyticsProcessManager] [node1] [z-ember-outlier4] Stopping process
[2020-08-22T13:57:30,497][DEBUG][o.e.x.m.d.e.DataFrameDataExtractor] [node1] [z-ember-outlier4] Data extractor was cancelled
[2020-08-22T13:57:30,497][DEBUG][o.e.x.m.p.AbstractNativeProcess] [node1] [z-ember-outlier4] Killing analytics process
[2020-08-22T13:57:30,497][DEBUG][o.e.x.m.p.NativeController] [node1] Killing process with PID: 12949
[2020-08-22T13:57:30,499][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [node1] [controller/8928] [CDetachedProcessSpawner.cc@99] Will not attempt to kill process 12949: not a child process
[2020-08-22T13:57:30,499][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [node1] [controller/8928] [CCommandProcessor.cc@96] Failed to kill process with PID 12949
[2020-08-22T13:57:30,488][DEBUG][o.e.x.m.p.ProcessResultsParser] [node1] io error while parsing
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 2, column: 1])
 at [Source: (FileInputStream); line: 15, column: 1]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664) ~[jackson-core-2.10.4.jar:2.10.4]
        at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:486) ~[jackson-core-2.10.4.jar:2.10.4]
        at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:498) ~[jackson-core-2.10.4.jar:2.10.4]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:3030) ~[jackson-core-2.10.4.jar:2.10.4]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3000) ~[jackson-core-2.10.4.jar:2.10.4]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:716) ~[jackson-core-2.10.4.jar:2.10.4]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52) ~[elasticsearch-x-content-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ml.process.ProcessResultsParser$ResultIterator.hasNext(ProcessResultsParser.java:70) [x-pack-ml-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ml.dataframe.process.AnalyticsResultProcessor.process(AnalyticsResultProcessor.java:106) [x-pack-ml-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ml.dataframe.process.AnalyticsProcessManager.lambda$runJob$0(AnalyticsProcessManager.java:145) [x-pack-ml-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:647) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by sophiec20** [comment]
Closing. Summary of investigation by @edsavage 

- If the CPP process had crashed due to an internally detected error any error messages would have been appended to the Java one saying it had stopped unexpectedly
- Signal 9 (SIGKILL) can't be caught, when sent to a process the process dies immediately so no chance to log anything extra anyway
- The crash handler is present for all native apps - limited usefulness for directly debugging the app only as it doesn't send log messages to the Java process
