### ISSUE TITLE
[ML] Unexpected failures in integration tests changing distribution generator

### ISSUE THREAD

**Issue by tveasey** [elastic/ml-cpp#901]
Changing distribution generator used to break ties in `CQuantileSketch` from `boost::random::uniform_01` to `std::uniform_real_distribution` causes the following unexpected integration test failures:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsHundred" -Dtests.seed=8A3A5CC6F4804780 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=UCT -Dcompiler.java=13
    java.lang.AssertionError:
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([8A3A5CC6F4804780:D22211090BFF5E96]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertModelStatePersisted(MlNativeDataFrameAnalyticsIntegTestCase.java:282)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsHundred(ClassificationIT.java:139)


REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsKeyword" -Dtests.seed=8A3A5CC6F4804780 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=UCT -Dcompiler.java=13
org.elasticsearch.xpack.ml.integration.ClassificationIT > testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsKeyword FAILED
    java.lang.AssertionError:
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([8A3A5CC6F4804780:951CD433D8811756]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertModelStatePersisted(MlNativeDataFrameAnalyticsIntegTestCase.java:282)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(ClassificationIT.java:200)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsKeyword(ClassificationIT.java:213)

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows" -Dtests.seed=8A3A5CC6F4804780 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=UCT -Dcompiler.java=13

org.elasticsearch.xpack.ml.integration.ClassificationIT > testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows FAILED
    java.lang.AssertionError:
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([8A3A5CC6F4804780:9E2EF94FB8764B89]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertModelStatePersisted(MlNativeDataFrameAnalyticsIntegTestCase.java:282)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows(ClassificationIT.java:98)

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsInteger" -Dtests.seed=8A3A5CC6F4804780 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=UCT -Dcompiler.java=13

org.elasticsearch.xpack.ml.integration.ClassificationIT > testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsInteger FAILED
    java.lang.AssertionError:
    Expected: <1>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([8A3A5CC6F4804780:A0B70A97EEB6FA1A]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertModelStatePersisted(MlNativeDataFrameAnalyticsIntegTestCase.java:282)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(ClassificationIT.java:200)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsInteger(ClassificationIT.java:219)
```

**Comment by tveasey** [comment]
This was raised in error. The failure was caused by not merging master to the feature branch, but I mistakenly thought this was caused by the change to the distribution generator because it didn't reproduce with that change reverted. In fact, it didn't reproduce because my elasticsearch branch was also out of date :(.
